# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-push: # job name
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    working_directory: ~/app
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build Docker images
          command: |
            echo "Inside the Build Docker image step"
            docker --version # print the version for logging
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t reverseproxy ./udagram-reverseproxy
      - run:
          name: Tagging Docker images
          command: |
            echo "Inside the tagging Docker image step"
            docker tag udagram-api-feed quangnd20/udagram-api-feed:1.0.0
            docker tag udagram-api-user quangnd20/udagram-api-user:1.0.0
            docker tag udagram-frontend quangnd20/udagram-frontend:1.0.0
            docker tag reverseproxy quangnd20/reverseproxy:1.0.0
      - run:
          name: Push Docker images
          command: |
            echo "Inside the push Docker image step"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push quangnd20/udagram-api-feed:1.0.0
            docker push quangnd20/udagram-api-user:1.0.0
            docker push quangnd20/udagram-frontend:1.0.0
            docker push quangnd20/reverseproxy:1.0.0

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-push-workflow:
    jobs:
      - build-and-push
